language: cpp
compiler:
  - clang
  - gcc
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost1.48-dev libsdl1.2-dev libsdl-mixer1.2-dev libpixman-1-dev doxygen
  - cmake -D CMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE builds/cmake
script: make
after_script:
  - make test
env:
  matrix:
    - CMAKE_BUILD_TYPE=DEBUG
    - CMAKE_BUILD_TYPE=RELEASE
