language: cpp
compiler:
  - clang
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost1.48-dev libsdl1.2-dev libsdl-mixer1.2-dev libpixman-1-dev
  - CXX="$CXX $WORKAROUND_CXX_FLAGS" cmake -D CMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE .
  - git clone --branch dummy "https://github.com/take-cheeze/RTP.git" $RPG_RTP_PATH
script: make all test
env:
  global:
    - WORKAROUND_CXX_FLAGS="-DBOOST_NO_CXX11_SMART_PTR -DBOOST_NO_CXX11_HDR_ARRAY -DBOOST_NO_RTTI -DBOOST_NO_TYPEID"
    - RPG_RTP_PATH="./lib/RTP"
  matrix:
    - CMAKE_BUILD_TYPE=DEBUG
    - CMAKE_BUILD_TYPE=RELEASE
