language: cpp
compiler:
  - clang
  - gcc
before_script:
  - echo "\n" | sudo add-apt-repository ppa:costamagnagianfranco/autoconf
  - echo "\n" | sudo add-apt-repository ppa:zoogie/sdl2-snapshots
  - sudo apt-get update -qq
  - sudo apt-get install -qq autoconf libboost1.48-dev libsdl2-dev libsdl2-mixer-dev libpixman-1-dev
  - mkdir m4
  - autoreconf -i
  - ./configure CXXFLAGS="-O0 -Wall -Wextra -ansi -pedantic"
script: make distcheck
after_script:
  - cat lib/TestGame/TestGame-2000/easyrpg_log.txt
  - cat Testing/Temporary/LastTest.log
